import numpy as np
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
#mathematical operations
print(a)
print(b)
print("Mathematical operations")
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print("Scaler operations")
print(a + 3)
print(a - 3)
print(a * 3)
print(a / 3)
print(a ** 3)
print("Other mathematical functions")
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
